#IOTA Lattice Compare - 1IO and 2IO

I took at look at the R-matrices as well as the lattice elements within the 1IO and 2IO lattices, and decided to put them in this notebook. I may add on to it in the future to keep track of lattice functions, tunes, etc. in case of future need.

In [1]:
%load_ext watermark
%load_ext autoreload
%autoreload 2

In [2]:
%watermark -d -v -a "Nathan Cook"

Nathan Cook 13/08/2015 

CPython 2.7.10
IPython 3.1.0


In [2]:
import sys, os
import synergia
from mpi4py import MPI
import synergia_workflow

import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from base_diagnostics import read_bunch
from base_diagnostics import workflow
from elliptic import EllipticBeam6D
from base_diagnostics import lfplot

##Construct the R-matrix from the remainder of the IOTA lattice 1IO

In [17]:
lattice = synergia.lattice.MadX_reader().get_lattice("iota","/Users/ncook/Synergia_Tests/lattices/Iota6-6/lattice_1IO_bare.madx")
lattice1IO = lattice

#10 steps per element
nsteps_per_element = 10
nsteps = len(lattice.get_elements())*nsteps_per_element
        
name = 'iota_bare'
order = 1
outputdir = 'order_'+str(order)+'_'+name
opts = workflow.make_opts(name, order, outputdir, nsteps, nsteps_per_element)

#need to construct stepper prior to lattice simulator to generate appropriate number of slices
stepper = synergia.simulation.Independent_stepper_elements(lattice, opts.map_order, opts.steps_per_element)
lattice_simulator = stepper.get_lattice_simulator()

#construct R-matrix from one-turn-map
bare_otm = lattice_simulator.get_linear_one_turn_map()
OTM = np.copy(bare_otm) #make a copy to pass to turn_end_action object
OTM_x = bare_OTM[0:2,0:2]
OTM_y = bare_OTM[2:4,2:4]

print 'Full R-Matrix:'
print
print OTM
print
print 'X component 2x2:'
print
print OTM_x
print
print 'Y component 2x2:'
print
print OTM_y
print
print 't-p component'
print
print OTM[4:6,4:6]

Full R-Matrix:

[[  1.00003870e+00  -4.03555423e-05   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.79732356e-06]
 [ -1.45446722e+00   1.00001999e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   5.65792130e-05]
 [  0.00000000e+00   0.00000000e+00   9.99949439e-01   6.06364824e-05
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00  -1.45447389e+00   9.99962365e-01
    0.00000000e+00   0.00000000e+00]
 [  5.91958922e-05  -1.79965313e-06   0.00000000e+00   0.00000000e+00
    1.00000000e+00   3.21622715e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00]]

X component 2x2:

[[  1.00003870e+00  -4.03555423e-05]
 [ -1.45446722e+00   1.00001999e+00]]

Y component 2x2:

[[  9.99949439e-01   6.06364824e-05]
 [ -1.45447389e+00   9.99962365e-01]]

t-p component

[[ 1.          3.21622715]
 [ 0.          1.        ]]


##Construct the R-matrix from the remainder of the IOTA lattice 2IO

In [19]:
lattice = synergia.lattice.MadX_reader().get_lattice("iota","/Users/ncook/Synergia_Tests/lattices/Iota6-6/lattice_2IO_bare.madx")
lattice2IO = lattice
#10 steps per element
nsteps_per_element = 10
nsteps = len(lattice.get_elements())*nsteps_per_element
        
name = 'iota_bare'
order = 1
outputdir = 'order_'+str(order)+'_'+name
opts = workflow.make_opts(name, order, outputdir, nsteps, nsteps_per_element)

#need to construct stepper prior to lattice simulator to generate appropriate number of slices
stepper = synergia.simulation.Independent_stepper_elements(lattice, opts.map_order, opts.steps_per_element)
lattice_simulator = stepper.get_lattice_simulator()

#construct R-matrix from one-turn-map
bare_otm = lattice_simulator.get_linear_one_turn_map()
OTM = np.copy(bare_otm) #make a copy to pass to turn_end_action object
OTM_x = bare_OTM[0:2,0:2]
OTM_y = bare_OTM[2:4,2:4]

print 'Full R-Matrix:'
print
print OTM
print
print 'X component 2x2:'
print
print OTM_x
print
print 'Y component 2x2:'
print
print OTM_y
print
print 't-p component'
print
print OTM[4:6,4:6]

Full R-Matrix:

[[  1.61802641e+00  -1.80000361e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   4.97556637e-07]
 [ -8.98881037e-01   1.61801383e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   5.76430934e-05]
 [  0.00000000e+00   0.00000000e+00   1.61803434e+00  -1.79997941e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00  -8.98980198e-01   1.61810277e+00
    0.00000000e+00   0.00000000e+00]
 [  9.37158318e-05  -1.04563432e-04   0.00000000e+00   0.00000000e+00
    1.00000000e+00   2.70329283e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00]]

X component 2x2:

[[  1.00003870e+00  -4.03555423e-05]
 [ -1.45446722e+00   1.00001999e+00]]

Y component 2x2:

[[  9.99949439e-01   6.06364824e-05]
 [ -1.45447389e+00   9.99962365e-01]]

t-p component

[[ 1.          2.70329283]
 [ 0.          1.        ]]


In [35]:
elems1IO = lattice1IO.get_elements()
elems2IO = lattice2IO.get_elements()

for index, elem in enumerate(elems1IO):
    elem2 = elems2IO[index]
    if elem.get_type() == elem2.get_type(): #check type
        da1 = elem.get_double_attributes()
        da2 = elem2.get_double_attributes()
        if da1.keys() == da2.keys(): #check double attribute keys
            for key in da1.keys(): #check double attribute values
                if not da1[key] == da2[key]:
                    print 'Variation in element double attribute: ' + str(key) + ' for element type ' + elem.get_type()
                    print '1IO element ' + str(elem.get_name()) + ' has value ' + str(da1[key])
                    print '2IO element ' + str(elem2.get_name()) + '  has value ' + str(da2[key])
        else:
            print 'Variation in element double attribute keys at element index' + str(index) + ' and element type ' + elem.get_type()
            print '1IO element ' + str(elem.get_name()) + ' has double attributes ' + str([key for key in da1.keys])
            print '2IO element ' + str(elem2.get_name()) + '  has double attribues ' + str([key for key in da2.keys])
    else:
        print 'Variation in element type at element index' + str(index)
        print '1IO element ' + str(elem.get_name()) + ' has type ' + elem.get_type()
        print '2IO element ' + str(elem2.get_name()) + ' has type ' + elem2.get_type()

Variation in element double attribute: k1 for element type quadrupole
1IO element qmb4r has value -8.072427002
2IO element qmb4r  has value -8.172122694
Variation in element double attribute: k1 for element type quadrupole
1IO element qmb5r has value 14.26726775
2IO element qmb5r  has value 13.8013101
Variation in element double attribute: k1 for element type quadrupole
1IO element qmb6r has value -11.88415788
2IO element qmb6r  has value -11.85115505
Variation in element double attribute: k1 for element type quadrupole
1IO element qmc1r has value -13.14610552
2IO element qmc1r  has value -12.76280335
Variation in element double attribute: k1 for element type quadrupole
1IO element qmc2r has value 11.98348508
2IO element qmc2r  has value 12.05684862
Variation in element double attribute: k1 for element type quadrupole
1IO element qmc3r has value -13.62421938
2IO element qmc3r  has value -13.43833468
Variation in element double attribute: k1 for element type quadrupole
1IO element qmd1r